name: Download TUGboat Issues

on:
  push:
  schedule:
    - cron: '0 6 3 * *'
  workflow_dispatch:

jobs:
  download_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the TUGboat downloader script
        run: python tugboat_downloader.py

      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v6
  keepalive:
    name: Keepalive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          commit_message: "Add new TUGboat issue"
